Dscf.SettleMents.Web/Controllers/PartialsController.cs
using Dscf.SettleMents.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dscf.SettleMents.Web.Controllers
{
    [ChildActionOnly]
    public class PartialsController : Controller
    {
        // GET: /Partial/
        public ActionResult TopNav()
        {
            var operCookie = LoginInfoHelper.Operater();
            ViewBag.OptName = operCookie.Name;
            //int optId = operCookie.Id;
            var platformList = LoginInfoHelper.GetAccessPlatformList();
            return PartialView(platformList);
        }

        /// <summary>
        /// 局部视图-左侧导航菜单
        /// </summary>
        /// <returns></returns>
        public ActionResult Menu()
        {

            var platformList = LoginInfoHelper.GetCurrentMenuList().OrderBy(item => item.Sort);
            return PartialView(platformList);
        }
    }
}

Dscf.SettleMents.Web/Views/Shared/NoAccess.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>没有权限-鼎盛财富</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="@Url.Content("~/Content/base.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/common.css")" rel="stylesheet" />
</head>
<body style="background-color:#f5f5f5">
    <div class="m-error">
        <p>Sorry,您没有访问权限！</p>
    </div>
</body>
</html>

Dscf.SettleMents.Web/Views/Shared/NotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>您所访问的页面不存在</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="@Url.Content("~/Content/base.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/common.css")" rel="stylesheet" />
</head>
<body style="background-color:#f5f5f5">
    <div class="m-error">
        <p>您所访问的页面不存在！</p>
    </div>
</body>
</html>

Dscf.SettleMents.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>@ViewBag.Title -鼎盛财富</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    @Styles.Render("~/Content/css")
    @RenderSection("css", required: false)
</head>

<body>
    <div class="mask_111" style="position: fixed; width: 100%; height: 105%; text-align: center; background: rgba(255, 255, 255, 0.5); z-index: 5555555; display: none; ">
        <div style=" width: 100px; height: 100px; margin: auto; position: absolute; top: 0; right: 0; bottom: 0; left: 0; ">
            <img src="/Content/images/lod.gif" style="opacity: 1">
        </div>
    </div>
    <div class="g-wraper">

        <!-- 头部开始 -->
        <div class="g-hd">
            <div class="m-header">
                <img src="@Url.Content("~/Content/images/header-bg.png")" class="bg" />
                <h1>
                    <a href="loding.html">
                        <img src="@Url.Content("~/Content/images/LOGO.png")" />
                    </a>
                </h1>
                @{ Html.RenderAction("TopNav", "Partials"); }
            </div>
        </div>
        <!-- 头部结束 -->

        <div class="g-bd1 f-cb">

            <!-- 左侧菜单开始 -->
            <div class="g-sd1 expandit">
                <div id="main-menu-wrapper">
                    @{ Html.RenderAction("Menu", "Partials"); }
                </div>
                <div class="sideDiv">
                    <a class="sidebar_toggle" href="#">
                        <i class="sidebar"></i>
                    </a>
                </div>
            </div>
            <!-- 左侧菜单结束 -->
            <!-- 内容部分开始 -->
            <div class="g-mn1" id="main-content">
                @RenderBody()
            </div>
            <!-- 内容部分结束 -->

        </div>

    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/dialog")
    @RenderSection("scripts", required: false)
</body>
</html>

Dscf.SettleMents.Web/Views/Shared/_PartialPager.cshtml
<div id="pager" style="float:left"></div>
<div style="float:left;margin-left:20px" id="selectCount">
    页面显示
    <select id="selelct_PageCount" style="font-size: 16px;height:38px;width:55px;" class="select">
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="5">5</option>
        <option selected="selected" value="10">10</option>
        <option value="20">20</option>
        <option value="30">30</option>
        <option value="50">50</option>
        <option value="100">100</option>
        <option value="200">200</option>
        <option value="500">500</option>
    </select>
    条
</div>